# Generated by Django 5.2.1 on 2025-05-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Очки за выполнение'),
        ),
    ]
