# Generated by Django 5.2.1 on 2025-05-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='points',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
