# Generated by Django 5.2.1 on 2025-05-28 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_points_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Очки за выполнение'),
        ),
        migrations.AddField(
            model_name='task',
            name='trigger_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='Триггер-задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='notification_method',
            field=models.CharField(blank=True, choices=[('none', 'Нет'), ('email', 'Email'), ('sms', 'СМС'), ('push', 'Push Notification')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_type',
            field=models.CharField(blank=True, choices=[('none', 'Нет'), ('one_time', 'Однократное'), ('periodic', 'Периодическое'), ('daily', 'Ежедневное'), ('trigger', 'По триггеру')], default='none', max_length=50),
        ),
    ]
